/* autogenerated by Processing revision 1295 on 2025-06-16 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class TWO_POINT_INTERFERENCE_PATTERN_SIMULATOR extends PApplet {

// TWO POINT INTERFERENCE PATTERN SIMULATOR
// TAEHYUN IM
// 2025.06.12

boolean showTitleScreen = true;

String[] asciiTitle = {
  "     +-+-+-+ +-+-+-+-+-+ +-+-+-+-+-+-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+     ",
  "      T  W O   P O I N T   I N T E R F E R E N C E   P A T T E R N      ",
  "     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+     ",
  "               B y   T a e h y u n   I m   ( B o y d )               ",
  "              +-+-+-+-+-+-+-+-+-+-+ +-+-+ +-+-+-+-+-+-+              ",
  "                         2 0 2 5 . 0 6 . 1 2                         ",
  "                        +-+-+-+-+-+-+-+-+-+-+                        ",
  "                                                                     ",
  "                     >>>  PRESS ENTER TO START  <<<                      "
};

float wavelength = 25;
float frequency = 1.5f;
float waveSpeed = 50;
float sourceDistance = 200;

boolean paused = false;
boolean showCircle = true;
boolean showDot = true;

PVector source1, source2;

float startTime;
float currentTime = 0;
float pausedStartTime = 0;
float totalPausedTime = 0;

public void setup() {
  ellipseMode(CENTER);
  textAlign(CENTER, CENTER);
  textSize(14);
  fill(0, 255, 255);
  noStroke();
  source1 = new PVector(width / 2 - sourceDistance / 2, height / 2);
  source2 = new PVector(width / 2 + sourceDistance / 2, height / 2);
  startTime = millis() / 1000.0f;
}

public void draw() {
  if (showTitleScreen) {
    drawTitleScreen();
    return;
  }

  background(0);

  if (!paused) {
    currentTime = millis() / 1000.0f - startTime - totalPausedTime;
  }

  waveSpeed = wavelength * frequency;
  source1.x = width / 2 - sourceDistance / 2;
  source2.x = width / 2 + sourceDistance / 2;

  if (showCircle) {
    drawWaveCircles(source1, currentTime);
    drawWaveCircles(source2, currentTime);
  }

  if (showDot) {
    drawNodalLines(source1, source2, currentTime);
  }

  drawLabels();

  fill(255, 0, 0);
  stroke(255, 0, 0);
  strokeWeight(4);
  ellipse(source1.x, source1.y, 10, 10);
  ellipse(source2.x, source2.y, 10, 10);
}

void drawTitleScreen() {
  background(0);
  fill(0, 255, 255);
  for (int i = 0; i < asciiTitle.length; i++) {
    text(asciiTitle[i], width / 2, height / 4 + i * 18 + 50);
  }
}

void drawWaveCircles(PVector source, float t) {
  noFill();
  strokeWeight(1.2f);
  stroke(255, 255, 255, 150);
  float maxRadius = t * waveSpeed;
  float startRadius = maxRadius % wavelength;
  for (float r = startRadius; r < maxRadius; r += wavelength) {
    ellipse(source.x, source.y, r * 2, r * 2);
  }
}

void drawNodalLines(PVector s1, PVector s2, float t) {
  float maxRadius = t * waveSpeed;
  float cx = (s1.x + s2.x) / 2.0f;
  float cy = (s1.y + s2.y) / 2.0f;
  float c = dist(s1.x, s1.y, s2.x, s2.y) / 2.0f;

  stroke(0, 255, 255);
  strokeWeight(1.5f);
  noFill();

  for (int m = 0; (m + 0.5f) * wavelength < maxRadius; m++) {
    float pathDiff = (m + 0.5f) * wavelength;
    float a = pathDiff / 2.0f;
    if (a >= c) continue;
    float b2 = c * c - a * a;

    for (int branch = -1; branch <= 1; branch += 2) {
      boolean shapeOpen = false;
      for (int py = 0; py <= height; py++) {
        float yRel = py - cy;
        float xRel = branch * a * sqrt(1.0f + (yRel * yRel) / b2);
        float px = cx + xRel;
        float d1 = dist(px, (float)py, s1.x, s1.y);
        float d2 = dist(px, (float)py, s2.x, s2.y);
        boolean inBounds = d1 <= maxRadius && d2 <= maxRadius && px >= 0 && px <= width;
        if (inBounds) {
          if (!shapeOpen) { beginShape(); shapeOpen = true; }
          vertex(px, py);
        } else {
          if (shapeOpen) { endShape(); shapeOpen = false; }
        }
      }
      if (shapeOpen) endShape();
    }
  }
}

void drawLabels() {
  fill(0, 0, 0, 150);
  noStroke();
  rect(5, 5, 200, 133);
  fill(0, 255, 255);
  textAlign(LEFT, CENTER);
  textSize(14);
  text("Wavelength (Q/A): " + nf(wavelength, 0, 1), 10, 25);
  text("Frequency (W/S): " + nf(frequency, 0, 1), 10, 45);
  text("Source Distance (E/D): " + nf(sourceDistance, 0, 1), 10, 65);
  text("Pause (SPACEBAR)", 10, 85);
  text("Toggle lines (r)", 10, 105);
  text("Toggle waves (f)", 10, 125);
}

public void keyPressed() {
  if (showTitleScreen && (key == ENTER || key == RETURN)) {
    showTitleScreen = false;
    startTime = millis() / 1000.0f;
    totalPausedTime = 0;
    paused = false;
    return;
  }

  if (key == 'q') wavelength += 1;
  if (key == 'a') wavelength -= 1;
  wavelength = constrain(wavelength, 5, 100);

  if (key == 'w') frequency += 0.1f;
  if (key == 's') frequency -= 0.1f;
  frequency = constrain(frequency, 0.1f, 5);

  if (key == 'e') sourceDistance += 5;
  if (key == 'd') sourceDistance -= 5;
  sourceDistance = constrain(sourceDistance, 10, 1000);

  if (key == 'r') showDot = !showDot;
  if (key == 'f') showCircle = !showCircle;

  if (key == ' ') {
    paused = !paused;
    if (paused) {
      pausedStartTime = millis() / 1000.0f;
    } else {
      totalPausedTime += millis() / 1000.0f - pausedStartTime;
    }
  }
}

  public void settings() { size(1000, 600); smooth(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "TWO_POINT_INTERFERENCE_PATTERN_SIMULATOR" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
